on:
  schedule:
    - cron:  '*/10 * * * *'
env:
  GIT_AUTHOR_NAME: mollybeach
  GIT_AUTHOR_EMAIL: mollyjbeach@gmail.com
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        echo "." >> README.md
        git add .
        git commit -m "Made changes to README"
        git push origin HEAD
